<a href="https://colab.research.google.com/github/Jahaira2002/ai2023-2_jahairaMacias/blob/main/Jahaira_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [ ]:
# Import numpy as np and see the version
# your code here
pass
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.23.5


In [ ]:
# Create a 1D array of numbers from 0 to 9  Aquí se está creando una matriz unidimensional arr y se imprime en la consola. np.arange, la almacena en la variable arr y luego imprime la matriz en la consola.
# your code here
pass
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0
pass

random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
print("Random vector with maximum value replaced:", random_vector)

Random vector with maximum value replaced: [0.49497835 0.59578215 0.         0.52161457 0.1373931  0.81520535
 0.64113789 0.29801467 0.68048208 0.65042174]


In [ ]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
pass

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 2])


8


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
pass


arr = np.array([1, 2, 3, 4, 5, 6, 7])

result = arr[2:5]

print(result)


[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
pass


arr = np.array([1, 2, 3, 4, 5, 6, 7])

result = arr[-4:]

print(result)


[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s
# your code here
pass

# Create a 3x3 array of all True's
true_array = np.ones((3, 3), dtype=bool)

print(true_array)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Extract all odd numbers from arr
# your code here
pass

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use boolean indexing to extract odd numbers
odd_numbers = arr[arr % 2 == 1]

print(odd_numbers)


[1 3 5 7 9]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
pass

# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last)
pass
def invertir_vector(vector):
    # Inicializa un nuevo vector vacío
    vector_invertido = []

    # Recorre el vector original en orden inverso y agrega elementos al nuevo vector
    for i in range(len(vector) - 1, -1, -1):
        vector_invertido.append(vector[i])

    return vector_invertido

# Ejemplo de uso
mi_vector = [1, 2, 3, 4, 5]
vector_invertido = invertir_vector(mi_vector)
print(vector_invertido)


[5, 4, 3, 2, 1]


In [ ]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
pass
a = np.random.randint(1, 100, size=(10, 10))
valor_minimo = np.min(a)
valor_maximo = np.max(a)

print("Matriz de 10x10 con valores aleatorios:")
print(a)
print(f"Valor mínimo: {valor_minimo}")
print(f"Valor máximo: {valor_maximo}")

Matriz de 10x10 con valores aleatorios:
[[29 43 33 86 13 44 27 95 64  1]
 [30 59 29 75 54 60 69 95 55 28]
 [45 35 66 16 52 22 76 97 44 90]
 [85 29 85 69 89 91 30 52 51 91]
 [98  7 69 71 75 41 67 41 73 20]
 [67 92 94 64 15 96 79 67 32 97]
 [38 69 50 97 84 66 18 14 86 23]
 [73 61 97 53 44 55 99 80 42 65]
 [27 65 12 98 19 91  5 63 46 81]
 [14 55 77 54 24 59  3 37 36 37]]
Valor mínimo: 1
Valor máximo: 99


In [ ]:
# Create a 3x3x3 array with random values
pass
a = np.random.rand(3, 3, 3)
print("3x3x3 array with random values:")
print(a)

3x3x3 array with random values:
[[[0.47385429 0.16747979 0.68270436]
  [0.02245127 0.44287961 0.91472621]
  [0.35763534 0.05521425 0.89368563]]

 [[0.8434047  0.04761596 0.42926233]
  [0.68355366 0.64130085 0.34007843]
  [0.59955398 0.42732727 0.56027986]]

 [[0.82524438 0.05284357 0.4553096 ]
  [0.57663724 0.47512504 0.87998363]
  [0.92697726 0.37145564 0.7254134 ]]]


In [ ]:
# Replace all odd numbers in arr with -1
# your code here
pass
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = [-1 if x % 2 != 0 else x for x in arr]
print(arr)

[-1, 2, -1, 4, -1, 6, -1, 8, -1]


In [ ]:
# Create an array of type float
pass

float_array = np.array([1.0, 2.5, 3.7, 4.2, 5.9], dtype=float)
print("Array of type float:")
print(float_array)

Array of type float:
[1.  2.5 3.7 4.2 5.9]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
pass
# Create a 1D array
one_dimensional_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Convert the 1D array to a 2D array with 2 rows
two_dimensional_array = one_dimensional_array.reshape(2, -1)

# The -1 in reshape allows NumPy to automatically calculate the number of columns
# to ensure the total number of elements remains the same.

print("1D Array:")
print(one_dimensional_array)

print("2D Array with 2 rows:")
print(two_dimensional_array)


1D Array:
[1 2 3 4 5 6 7 8]
2D Array with 2 rows:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)

# Create the two arrays Z1 and Z2 with random integer values
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Convert the NumPy arrays to Python sets
set_Z1 = set(Z1)
set_Z2 = set(Z2)

# Find the common values by taking the intersection of the sets
common_values = set_Z1.intersection(set_Z2)

# Convert the result back to a NumPy array if needed
common_values_array = np.array(list(common_values))

print("Z1 array:")
print(Z1)

print("Z2 array:")
print(Z2)

print("Common values:")
print(common_values_array)

pass

Z1 array:
[3 8 3 8 0 5 8 9 1 0]
Z2 array:
[2 8 5 7 2 0 9 9 3 3]
Common values:
[0 3 5 8 9]


In [ ]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

pass

# Create two random arrays A and B with integer values (0 or 1)
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:")
print(A)

print("Array B:")
print(B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Array A:
[0 0 0 0 1]
Array B:
[0 1 1 0 0]
Arrays A and B are not equal.


In [ ]:
# Stack arrays a and b vertically
# your code here
pass

# Create arrays a and b (for example)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack the arrays vertically
result = np.vstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked result:")
print(result)


Array a:
[1 2 3]
Array b:
[4 5 6]
Stacked result:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Stack the arrays a and b horizontally.
# your code here
pass
# Create arrays a and b (for example)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack the arrays horizontally
result = np.hstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked result:")
print(result)


Array a:
[1 2 3]
Array b:
[4 5 6]
Stacked result:
[1 2 3 4 5 6]


In [ ]:
# Get all items between 5 and 10 from array tmp.
# your code here

# pass

# Create a sample array
tmp = np.array([2, 6, 8, 3, 9, 1, 7, 10, 4, 5])

# Get items between 5 and 10
items_between_5_and_10 = tmp[(tmp >= 5) & (tmp <= 10)]

print("Original array (tmp):")
print(tmp)

print("Items between 5 and 10:")
print(items_between_5_and_10)


Original array (tmp):
[ 2  6  8  3  9  1  7 10  4  5]
Items between 5 and 10:
[ 6  8  9  7 10  5]


In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here

def pair_max(a, b):
    # Ensure that a and b are NumPy arrays for consistent element-wise operations
    a = np.array(a)
    b = np.array(b)

    # Calculate the element-wise maximum between a and b
    result = np.maximum(a, b)

    return result

# Example usage:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)


[6 7 9 8 9 7 5]


In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


# your code here
pass

# Create a sample array
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Swap columns 1 and 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print(arr)


[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

# Create a 5x3 array with random decimal numbers between 5 and 10
random_array = np.random.uniform(5, 10, (5, 3))

# Print the result
print(random_array)


[[8.75527391 5.97806601 5.37304236]
 [5.49518347 8.6396188  8.92589538]
 [6.91667625 6.3940603  7.38360252]
 [7.84257906 8.11541332 7.31595714]
 [5.40309866 6.52144595 6.71386631]]
