<a href="https://colab.research.google.com/github/Jahaira2002/ai2023-2_jahairaMacias/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

aux=np.array([1,2,4,5])
print(aux)
# Tipo de arreglo
print(aux.shape)
print('------------------------------')

aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
print('------------------------------')

tmp=np.zeros((4,4))
print(tmp)
print('------------------------------')


tmp=np.full((4,4),5)
print(tmp)
print('------------------------------')


tmp=np.eye(4,4)
print(tmp)
print('------------------------------')


tmp=np.ones((4,4))
print(tmp)
print('------------------------------')


[1 2 4 5]
(4,)
------------------------------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------------------


In [3]:
tmp=10*np.random.random((4,4))
print(tmp)
print('------------------------------')


[[0.11984573 5.07582113 5.58386145 4.12180228]
 [5.95380938 6.57967127 9.22679416 0.47351266]
 [4.70417845 9.10290713 0.288444   2.38470856]
 [4.65835955 8.20814696 9.40110307 9.26951105]]
------------------------------


In [4]:
print(tmp[:2,:2])
print('------------------------------')
print(tmp[2:4,2:4])


[[0.11984573 5.07582113]
 [5.95380938 6.57967127]]
------------------------------
[[0.288444   2.38470856]
 [9.40110307 9.26951105]]


In [5]:
print(tmp[1,1])
print('------------------------------')
print(tmp[2,2])
print('------------------------------')


6.579671265910743
------------------------------
0.28844400473476695
------------------------------


In [6]:
tmp=10*np.random.random((4,4))
print(tmp)

[[7.83027565 7.14047857 4.03206034 5.88524899]
 [2.93462717 5.0936303  3.56419619 6.41879322]
 [7.96383263 9.36518153 4.60916743 6.13974082]
 [9.01609293 9.74330261 4.95312092 2.76628931]]


In [7]:
mascara=tmp>5
print(mascara)
print('------------------------------')
print(tmp[mascara])
print('------------------------------')

[[ True  True False  True]
 [False  True False  True]
 [ True  True False  True]
 [ True  True False False]]
------------------------------
[7.83027565 7.14047857 5.88524899 5.0936303  6.41879322 7.96383263
 9.36518153 6.13974082 9.01609293 9.74330261]
------------------------------


In [8]:
mask = (tmp >=2) & (tmp<=4)
print(tmp[mask])

[2.93462717 3.56419619 2.76628931]


In [9]:
tmp = np.random.randint(0, 11, size=(4, 4))
print(tmp)
print('----------------------------------')
mask = np.mod(tmp, 2) == 0
print(tmp[mask])

[[ 6  9  8  7]
 [ 1  0  8  0]
 [ 2 10  3  2]
 [ 1  0  8  8]]
----------------------------------
[ 6  8  0  8  0  2 10  2  0  8  8]
