<a href="https://colab.research.google.com/github/Jahaira2002/ai2023-2_jahairaMacias/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#create an array with random inteher values between 1 and 10
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('Adding numbers')
#plus
print(a+b)
print('Subtracting numbers')
#minus
print(a-b)
print('Multiplication numbers')
#times
print(a*b)


print('Add')
print(np.add(a,b))
print('Substract')
print(np.multiply(a,b))
print('Multiply')
print(np.subtract(a,b))
print('Divide')
print(np.divide(a,b))


[[ 9  9  5  7]
 [ 4  9  6 10]
 [10 10 10  4]]
[[10  4  9 10]
 [ 8  1  2 10]
 [ 9  2  6  5]]
(3, 4)
(3, 4)
Adding numbers
[[19 13 14 17]
 [12 10  8 20]
 [19 12 16  9]]
Subtracting numbers
[[-1  5 -4 -3]
 [-4  8  4  0]
 [ 1  8  4 -1]]
Multiplication numbers
[[ 90  36  45  70]
 [ 32   9  12 100]
 [ 90  20  60  20]]
Add
[[19 13 14 17]
 [12 10  8 20]
 [19 12 16  9]]
Substract
[[ 90  36  45  70]
 [ 32   9  12 100]
 [ 90  20  60  20]]
Multiply
[[-1  5 -4 -3]
 [-4  8  4  0]
 [ 1  8  4 -1]]
Divide
[[0.9        2.25       0.55555556 0.7       ]
 [0.5        9.         3.         1.        ]
 [1.11111111 5.         1.66666667 0.8       ]]


In [2]:
m1 = np.random.randint(1, 11, size=(3,4))
m2 = np.random.randint(1, 11, size=(4,8))
print('Matriz 1')
print(m1)
print(m1.shape)
print('Matriz 2')
print(m2)
print(m2.shape)
print('-------------------------')
print('Forma 1')
print(np.dot(m1,m2))
print('Forma 2')
print(m1.dot(m2))
print(np.dot(m1,m2).shape)

Matriz 1
[[ 8  6  1  4]
 [ 8  8 10  9]
 [ 5  5  3  6]]
(3, 4)
Matriz 2
[[ 9 10  5  7 10  1  6  5]
 [ 9 10  9  1  5  3  2  9]
 [ 3  1  2 10  6  4  6  6]
 [ 6  4 10  3  4  1  9  6]]
(4, 8)
-------------------------
Forma 1
[[153 157 136  84 132  34 102 124]
 [228 206 222 191 216  81 205 226]
 [135 127 136  88 117  38 112 124]]
Forma 2
[[153 157 136  84 132  34 102 124]
 [228 206 222 191 216  81 205 226]
 [135 127 136  88 117  38 112 124]]
(3, 8)


In [3]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)


(2, 2)
<class 'numpy.ndarray'>
[[1 7]
 [6 9]]
[[1 6]
 [7 9]]


In [4]:
#broadcast
x = np.random.randint(1, 11, size=(4,3))
y = np.array([1,0,2])

print(x.shape)
print(y.shape)

z=np.empty_like(x)
print('---------------------')
print(x)
print('---------------------')
print(y)
print(z.shape)
print('---------------------')
print(z)


(4, 3)
(3,)
---------------------
[[ 9 10  4]
 [ 7  1  1]
 [ 8  5  9]
 [ 7 10  7]]
---------------------
[1 0 2]
(4, 3)
---------------------
[[4606281698874543309 4612248968380809216 4603179219131243634]
 [4604480259023595110 4602678819172646912 4621256167635550208]
 [4613937818241073152 4607182418800017408 4607682818758614130]
 [4617315517961601024 4610184818551597739 4605380978949069210]]


In [5]:
for i in range(4):
  z[i,:]=x[i,:]+y
print(z)

[[10 10  6]
 [ 8  1  3]
 [ 9  5 11]
 [ 8 10  9]]


In [6]:
z=x+y
print(z)


[[10 10  6]
 [ 8  1  3]
 [ 9  5 11]
 [ 8 10  9]]


In [7]:
#para comentar varias lineas de codigo se usa triple comillas simples """  """

a=np.array([1,2,3])
print(a)
print('-----------------')

b = np.full((6,3),[a])
print(b)
print('-----------------')

c= np.tile(a,(6,1))
print(c)

[1 2 3]
-----------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
-----------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
m1 = np.random.randint(0, 10, size=(6,6))
print(m1)
aux=np.mean(m1)
print(aux)

np.mean(m1, axis=1) #promedio por filas
np.mean(m1, axis=0) #promedio por filas

print('Promedio por filas')
print(np.mean(m1, axis=1))
print('Promedio por columnas')
print(np.mean(m1, axis=0))

[[8 6 8 8 0 5]
 [6 6 2 7 4 8]
 [3 6 6 6 4 2]
 [2 0 6 9 6 3]
 [2 1 7 7 6 1]
 [8 8 2 6 4 2]]
4.861111111111111
Promedio por filas
[5.83333333 5.5        4.5        4.33333333 4.         5.        ]
Promedio por columnas
[4.83333333 4.5        5.16666667 7.16666667 4.         3.5       ]
